// lib/product-list-mock.ts
import { CategoryFilterItem, PaginationMeta, ProductItemData } from '@/types/product-list';

export const MOCK_CATEGORIES: CategoryFilterItem[] = [
  { id: 'cat-1', name: 'Tất cả món', slug: 'all', count: 48, icon: 'lunch_dining' },
  { id: 'cat-2', name: 'Burger & Combo', slug: 'burger', count: 14, icon: 'fastfood' },
  { id: 'cat-3', name: 'Gà Rán & Đồ Chiên', slug: 'fried-chicken', count: 12, icon: 'restaurant' },
  { id: 'cat-4', name: 'Trà Sữa & Nước Giải Khát', slug: 'drinks', count: 15, icon: 'local_cafe' },
  { id: 'cat-5', name: 'Tráng Miệng & Ăn Vặt', slug: 'snacks', count: 7, icon: 'cake' },
];

export const MOCK_PRODUCTS: ProductItemData[] = [
  {
    id: 'prod-01',
    name: 'Burger Bò Phô Mai Hai Tầng Đặc Biệt',
    slug: 'burger-bo-pho-mai-2-tang',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80',
    price: 79000,
    originalPrice: 99000,
    discountPercentage: 20,
    rating: 4.8,
    reviewCount: 124,
    stock: 15,
    isNew: true,
    categoryName: 'Burger & Combo',
  },
  {
    id: 'prod-02',
    name: 'Trà Sữa Đào Cam Sả Size L (Ít Đường)',
    slug: 'tra-sua-dao-cam-sa',
    imageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&auto=format&fit=crop&q=80',
    price: 45000,
    originalPrice: 55000,
    discountPercentage: 18,
    rating: 4.9,
    reviewCount: 89,
    stock: 40,
    isNew: false,
    categoryName: 'Trà Sữa & Nước Giải Khát',
  },
  {
    id: 'prod-03',
    name: 'Combo Gà Rán Sốt Cay Hàn Quốc + Pepsi',
    slug: 'combo-ga-ran-sot-cay',
    imageUrl: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=600&auto=format&fit=crop&q=80',
    price: 89000,
    originalPrice: 115000,
    discountPercentage: 22,
    rating: 4.7,
    reviewCount: 210,
    stock: 0,
    isNew: false,
    categoryName: 'Gà Rán & Đồ Chiên',
  },
  {
    id: 'prod-04',
    name: 'Khoai Tây Chiên Lắc Phô Mai Bơ Tỏi',
    slug: 'khoai-tay-chien-lac-pho-mai',
    imageUrl: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=600&auto=format&fit=crop&q=80',
    price: 35000,
    originalPrice: 45000,
    discountPercentage: 22,
    rating: 4.6,
    reviewCount: 56,
    stock: 25,
    isNew: true,
    categoryName: 'Tráng Miệng & Ăn Vặt',
  },
  {
    id: 'prod-05',
    name: 'Cơm Gà Sốt Teriyaki Nhật Bản',
    slug: 'com-ga-sot-teriyaki',
    imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&auto=format&fit=crop&q=80',
    price: 65000,
    originalPrice: 80000,
    discountPercentage: 19,
    rating: 4.5,
    reviewCount: 77,
    stock: 8,
    isNew: false,
    categoryName: 'Burger & Combo',
  },
  {
    id: 'prod-06',
    name: 'Cà Phê Đen Đá Truyền Thống',
    slug: 'ca-phe-den-da',
    imageUrl: 'https://images.unsplash.com/photo-1611564494260-6f21b80af7ea?w=600&auto=format&fit=crop&q=80',
    price: 25000,
    originalPrice: 30000,
    discountPercentage: 17,
    rating: 4.9,
    reviewCount: 312,
    stock: 100,
    isNew: false,
    categoryName: 'Trà Sữa & Nước Giải Khát',
  },
  {
    id: 'prod-07',
    name: 'Pizza Mini Xúc Xích Nấm',
    slug: 'pizza-mini-xuc-xich-nam',
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80',
    price: 55000,
    originalPrice: 70000,
    discountPercentage: 21,
    rating: 4.4,
    reviewCount: 43,
    stock: 12,
    isNew: true,
    categoryName: 'Tráng Miệng & Ăn Vặt',
  },
  {
    id: 'prod-08',
    name: 'Chè Bưởi Sầu Riêng Thập Cẩm',
    slug: 'che-buoi-sau-rieng',
    imageUrl: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=600&auto=format&fit=crop&q=80',
    price: 29000,
    originalPrice: 35000,
    discountPercentage: 17,
    rating: 4.7,
    reviewCount: 61,
    stock: 0,
    isNew: false,
    categoryName: 'Tráng Miệng & Ăn Vặt',
  },
];

export const MOCK_PAGINATION: PaginationMeta = {
  currentPage: 1,
  totalPages: 4,
  pageSize: 12,
  totalItems: 48,
};
